name: Release
on:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the release version
        id: get_version
        run: |
          VELA_VERSION=${GITHUB_REF#refs/tags/} \
          echo ${VELA_VERSION} \
          PYTHON_VELA_VERSION=`echo ${VELA_VERSION} | grep -Eo "(\d+\.)+\d"` \
          echo ${PYTHON_VELA_VERSION} \
          echo ::set-output name=VERSION::${PYTHON_VELA_VERSION} \

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate version file
        run: |
          cd ${{ github.workspace }} && \
          echo "${{ github.event.repository.name }},version,${{ steps.get_version.outputs.VERSION }}" >> version.txt && \
          echo "${{ github.event.repository.name }},commit_hash,${GITHUB_SHA}" >> version.txt \

      - name: Upload version file
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: version.txt
          asset_name: version.txt
          asset_content_type: text/plain

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Replace setup cfg
        run: |
          sed -i -e 's/version = .*$/version = ${{ steps.get_version.outputs.VERSION }}/g' setup.cfg
          cat setup.cfg

      - name: Build DongTai Core Package
        run: |
          python setup.py sdist
          ls ./dist

      - name: Upload tar file
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/dongtai-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: ./dist/dongtai-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip
